/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/nintendo.glb --types 
Author: Marcos Silva (https://sketchfab.com/marcosramone25)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-nintendo-snes-controller-ccb65460e0554b5ab833bf94e87a8fdb
Title: Super Nintendo (SNES) Controller
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
    defaultMaterial_1: THREE.Mesh
    defaultMaterial_2: THREE.Mesh
    defaultMaterial_3: THREE.Mesh
  }
  materials: {
    lambert9SG_1002: THREE.MeshStandardMaterial
    lambert9SG_1001: THREE.MeshStandardMaterial
    lambert9SG_1003: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/nintendo.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert9SG_1002} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert9SG_1002} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert9SG_1001} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert9SG_1003} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/nintendo.glb')
