/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/world.glb --types 
Author: PounUP (https://sketchfab.com/PounUP)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/planet-0104234961624b7aa0cb85d03161babe
Title: Planet
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    COMBINE_LP_LAM_0: THREE.Mesh
    COMBINE_LP_1_0: THREE.Mesh
    COMBINE_LP_2_0: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/world.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.334, -0.782, 1.171]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.COMBINE_LP_LAM_0.geometry} material={materials.material} />
        <mesh geometry={nodes.COMBINE_LP_1_0.geometry} material={materials.material_1} />
        <mesh geometry={nodes.COMBINE_LP_2_0.geometry} material={materials.material_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/world.glb')
